api:
 url: http://api.openweathermap.org/data/2.5/weather?
 key: 80ef4f9656b54e6e700d5545afc4f41a
 groupurl: http://api.openweathermap.org/data/2.5/group?

 

spring:
 output:
  ansi:
   enabled: ALWAYS
   
 
  
env:
   desc: dev
---
spring:
 profiles: dev
 
env:
   desc: dev
---

spring:
 profiles: test
 
env:
   desc: test
---
spring:
   profiles: prod
env:
   desc: prod   

devtools:
  restart:
   additional-paths: .
   
   
hystrix:
 command:
  getWeatherApi:
   circuitBreaker:
    requestVolumeThreshold: 2
    



   metrics:
    rollingStats:
     timeInMilliseconds: 500
     

  default:
   circuitBreaker:
    errorThresholdPercentage: 1
    

    sleepWindowInMilliseconds: 1000
    

    getWeatherApi:
     execution:
      isolation:
       thread:
        timeoutInMilliseconds: 2000
        


management:
  endpoints:
    web:
      exposure:
        include: "*"
        
        



   
   
